name: hello-world

on: 
  
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]


jobs:
  # Build Job
  # test:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Install Node
  #       uses: actions/setup-node@v3

  #       with:
  #         node-version: 18.x

  #     - name: Install Dependencies
  #       run: npm install

  #     - name: Build Project
  #       run: npm run build

  #     - name: Upload artifact to enable deployment
  #       uses: actions/upload-artifact@v3

  #       with:
  #         name: production-files
  #         path: ./dist

  deploy:
    runs-on: ubuntu-latest
    # needs: test

    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}

        script: |
          
          chmod +x /home/salom/.scripts/deploy.sh
          cd /home/salom && git stash && ./.scripts/deploy.sh
          
