name: Ci

on: 
  
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]


jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}

        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          # whoami
          # cd /home/salom
          git stash
          git pull
          npm install --yes
          npm run build

    - name: send custom message with args
      if: always()
      
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          
          ${{ job.status == 'success' && '✅✅✅ Deployment muvaffaqiyatli yakunlandi!' || '❌❌❌ Xatolik yuz berdi!' }}
          Status: ${{ job.status }},
          