name: hello-world

on: 
  
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # Build Job
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3

        with:
          node-version: 18.x

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Upload artifact to enable deployment
        uses: actions/upload-artifact@v3

        with:
          name: production-files
          path: ./dist
      
      # - name: Send Telegram notification
      #   if: success()
      #   run: |
      #     curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage" \
      #     -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
      #     -d text="Build successful! 🎉"

  

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10

        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd /home/github-runner/salom
            git stash
            git pull
            npm install
            npm run build
  