name: Ci

on: 
  
  push:
    branches: ["main"]
  
  pull_request:
    branches: ["main"]


jobs:
  # Build Job
  # test:

  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

      # - name: Install Node
      #   uses: actions/setup-node@v3

      #   with:
      #     node-version: 18.x

      # - name: Install Dependencies
      #   run: npm install

      # - name: Build Project
      #   run: npm run build


  deploy:
    runs-on: ubuntu-latest
    # needs: test

    steps:

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}

        script: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

          whoami
          cd /home/salom1
          git stash
          git pull
          npm install --yes
          npm run build
    - name: send custom message with args
      if: always()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ job.status == 'success' && '🚀 Deployment muvaffaqiyatli yakunlandi!' || '❌ Xatolik yuz berdi!' }}
          Make ${{ github.event_name }}. 
          Job ${{github.job}}, 
          Status: ${{github.action_status}},
          action ${{github.action}}
          # Commit message: ${{ (github.event.commits[0].message )}}
          # Status: ${{ (github.job_status) }}
          Error Details: ${{ (steps.deploy.out.err) }}
        
    # - name: Notify Telegram on Success
    #   if: success()
    #   run: |
    #     curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
    #     -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    #     -d text="🚀 Deployment muvaffaqiyatli yakunlandi!"
    
    # - name: Notify Telegram on Failure
    #   if: failure()
    #   run: |
    #     echo "Error Details: ${{ steps.deploy.outputs.error }}"
    #     curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
    #     -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
    #     -d text="❌ Xatolik yuz berdi! Iltimos, jarayonni tekshiring.\n\nError Details: ${{ steps.deploy.outputs.error }}"